document xpath issue with javascript
taranis-ai/taranis.ai pull request #31
Opened 2024-07-23 13:09 UTC by not4Pedro

inform about XPath issues with JavaScript

2024-07-23 13:32 UTC, b3n4kh requested changes

2024-07-23 13:32 UTC, b3n4kh commented on content/en/docs/admin/collectors.md
> +_Note: Digest splitting can fail if the web page contains JavaScript. As of now, there is no workaround but it might be improved in the future releases._
Simple Web Collector will fail if the web page content is only available with JavaScript. Switching to the Selenium based "Web Collector" will allow parsing JavaScript based websites, but as of right now "Web Collector" does not support Digest Splitting


Remove the _Note: at the bottom.

2024-08-05 14:32 UTC, not4Pedro commented
related to issue [#290](https://github.com/orgs/taranis-ai/projects/1/views/1?pane=issue&itemId=71908503)

2024-08-07 09:59 UTC, not4Pedro commented
Now the Selenium Collector is removed, and support for javascript is added to the Simple Web Collector

2024-08-13 18:28 UTC, merged